#Version incremented before build
<<<<<<< HEAD
#Tue Apr 07 22:23:17 CEST 2026
lastFeatureKey=028
versionCode=300
versionName=0.15.6
=======
#Tue Apr 07 14:43:24 UTC 2026
lastFeatureKey=027
versionCode=292
versionName=0.14.21
>>>>>>> origin/main
